### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by amskywalker** [IsraelJito/PHPBlog#1]
Try to give more details about how the project works. | **ENGLISH**

Tente organizar o seu README.md, para dizer o que é, e como funciona o seu projeto.   |  **PORTUGUESE**

**Comment by IsraelJito** [comment]
Thank you, i am still just getting acquainted with github

**Comment by amskywalker** [comment]
If u need help, you can contact me on social networks, just visit my profile. I liked your project
Good Luck

**Comment by IsraelJito** [comment]
Thanks bro, nice to meet you. i followed your twitter account, my twitter
name is @israelosaivbie

**Comment by IsraelJito** [comment]
which of my project was that?

**Comment by amskywalker** [comment]
PHPBlog, very cool

**Comment by IsraelJito** [comment]
Thanks mate I hope we would talk on twitter?

**Comment by amskywalker** [comment]
Me too you can contact me.
